version = 0.1

[default.deploy.parameters]
stack_name = "llm-wikipedia-scraper"
region = "ap-south-1"
profile = "default"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
fail_on_empty_changeset = false
image_repositories = []
disable_rollback = true
resolve_s3 = true
s3_prefix = "llm-wikipedia-scraper"
