version = 0.1

[default.deploy.parameters]
stack_name = "wiki-scraper-backend"
region = "ap-south-1"
profile = "default"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
s3_prefix = "wiki-scraper-backend"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
no_execute_changeset = false
no_fail_on_empty_changeset = false
use_json = true
disable_rollback = true

[default.build.parameters]
use_container = false
cached = true
parallel = true

[default.sync.parameters]
watch = true
code = true

[default.package.parameters]
s3_bucket = "wiki-scraper-deployment"
s3_prefix = "wiki-scraper-backend"
output_template_file = "packaged.yaml"
use_json = true
