AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Wiki Scraper API with Puppeteer

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  ScraperQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub wiki-scraper-queue-${EnvironmentName}
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600

  ScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub wiki-scraper-${EnvironmentName}
      CodeUri: ./
      Handler: dist/api.handler
      Runtime: nodejs18.x
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          NODE_ENV: !Ref EnvironmentName
          QUEUE_URL: !Ref ScraperQueue
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          CHROME_BIN: /opt/chromium/headless_shell
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:764866452798:layer:chrome-aws-lambda:31'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /scrape
            Method: post
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ScraperQueue.QueueName

  ScraperApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub wiki-scraper-api-${EnvironmentName}
      Description: API Gateway for Wiki Scraper
      EndpointConfiguration:
        Types:
          - REGIONAL

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ScraperApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrape"
  QueueUrl:
    Description: "SQS Queue URL"
    Value: !Ref ScraperQueue
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref ScraperFunction
