version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DEFAULT_REGION=ap-south-1
    volumes:
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wiki-scraper-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-south-1
      - QUEUE_URL=http://localstack:4566/000000000000/scraper-queue
    volumes:
      - .:/var/task
      - /var/task/node_modules
      - ./logs:/var/task/logs
    working_dir: /var/task
    command: >
      sh -c "npm install && 
             npm run build &&
             mkdir -p logs &&
             sam local start-api --docker-network wiki-scraper_default --host 0.0.0.0 --port 3000"
